### ISSUE TITLE
_CMD_LINE cannot be used with double-dashed arguments

### ISSUE THREAD

**Issue by eedwardsav** [rerun/rerun#239]
_CMD_LINE is documented as a way to pass remaining command line arguments to an underlying executable

However, rerun will automatically attempt to parse anything on the command line that starts with double-dashes `--`, preventing the ability to pass command line arguments down to an executable that uses double-dashed arguments, as well.

A suggested improvement would be to allow unrecognized options to be passed onto _CMD_LINE

e.g.

if I have an executable with this supported option:

`myexe --myexe-option`

allow me to specify it on the command line without first creating an official 'option' for it:

`rerun myexewrapper:execute --rerun-option --myexe-option`

**Comment by eedwardsav** [comment]
I'm looking into adding a STRICT setting to allow optionally defining the check for arguments during generate-options

**Comment by stagrlee** [comment]
I think https://github.com/rerun/rerun/issues/229 was implemented incomplete.  It supports single dashed arguments but not double dashed arguments getting passed through option parsing.  Lets redo the implementation with eye towards finishing https://github.com/rerun/rerun/issues/229 instead of trying to maintain backward compatibility.  Right now, this issue is pointing out a bug in the implementation not meeting the documentation.  @ahonor need you to look at this.  Want to make the behavior of rerun going forward to not fail if a double dash option is encountered that it does not recognize.

**Comment by eedwardsav** [comment]
@stagrlee @ahonor created PR #241 with a simple approach to address this

**Comment by eedwardsav** [comment]
Closed #241 in favor of #242

**Comment by eedwardsav** [comment]
This was fixed in #244
